### PR TITLE
[WIP] Alternative source for kratos binaries

### PR DESCRIPTION
**Pull request by roigcarlo**
This should fix future problems with the servers and https://github.com/simphony/simphony-framework/issues/52.
- [ ] Upload the correct build.

### CODE REVIEW

**Comment by itziakos** [comment]
@roigcarlo the requirements file is installing simphony master. I guess you need to force installing simphony 0.1.3 or 0.15

**Comment by roigcarlo** [comment]
@itziakos This will fix simphony/simphony-framework#52.

I will merge this as soon as the correct version is uploaded ( I need access to either the old server or the compile server, which are both down... )

**Comment by itziakos** [comment]
Thanks @roigcarlo

**Comment by itziakos** [comment]
@roigcarlo, I have updated the requirements file it should install the correct version now

**Comment by roigcarlo** [comment]
@itziakos thx

**Comment by roigcarlo** [comment]
Closing this PR without merge since it doesn't have relevant changes anymore.
- Kratos source has been fixed ( may be subject to change in the future but will be adressed in a separate PR )
- Versioning is being worked on in the release branch for simphony 0.4.0

**Pull request closed without merging**
